switched to SecureStore/fixed onboarding chore and reward submission bug/android UI fixes
kiddiekredit/kkfrontend pull request #23
Opened 2021-04-21 17:57 UTC by michaeldegori

switched to SecureStore/fixed onboarding chore and reward submission bug/android UI fixes

2021-04-21 19:28 UTC, Swolebrain requested changes

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/AddFamilyUnitMember/AddChildView.js
> +										value={null}
this seems broken.

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/AddFamilyUnitMember/AddChildView.js
> +										value={null}
here too

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/AddFamilyUnitMember/AddChildView.js
> +										value={null}
also here

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/Alerts/AlertsView.js
> +		style={{ paddingTop: Platform.OS === 'android' ? getStatusBarPadding() : 0 }}
why not put the platform conditional in the getStatusBarPadding function? Seems like this funtion is incomplete

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/KreditDashboard/KidKreditDashboardView.js
> +			paddingTop: Platform.OS === 'android' ? getStatusBarPadding() : 0,
getStatusBarHeight should do this

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/KreditDashboard/KreditDashboardView.js
> +	showBBModal,
this is very redundant. You never need a "Show" and a "hide" variable for the same thing. It seems like three variables are related to the same thing here. Only one piece of state is needed to determine whether the modal is visible or not.

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/KreditDashboard/KreditDashboardView.js
> +	setBBs,
subtractBBs and setBBs are redundant. Subtracting is just adding a negative number. We need to reduce code repetition here.

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/KreditDashboard/index.js
> +		this.setState({ bambooBucks: (this.state.bambooBucks -= 1) });
when adding or subtracting 1, it is bad practice to not use functional setstate. Please read https://www.freecodecamp.org/news/functional-setstate-is-the-future-of-react-374f30401b6b/

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/RewardsFeed/KidRewardsView.js
> +			paddingTop: Platform.OS === 'android' ? getStatusBarPadding() : 0,
repetitive here too

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/Settings/TermsOfUse.js
> +import { ActivityIndicator, Dimensions, View } from 'react-native';
please turn off your automatic formatting or be more mindful of what you commit. These non-changes are cluttering the PR process.

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/onboarding/OnboardingChoreSuggestionsContainer.js
> +		this.setState({
once again please don't add things from the repository to local state. Very bad practice and bug prone. The point of a repository is to not need local state for that thing.

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/onboarding/OnboardingChoreSuggestionsContainer.js
>  			{
please move all these to a separate file.

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/onboarding/OnboardingChoreSuggestionsContainer.js
> +			const existingChore = this.state.existingChores.find(eachChore => eachChore.name === chore.name);
is this line extraneous?

2021-04-21 19:28 UTC, Swolebrain commented on src/routes/onboarding/OnboardingRewardSuggestionsContainer.js
> +	handleCheck = reward => {
this is bug-prone. Bad practice to rely on current state to set new state. Read the article I posted on functional setState.

2021-04-21 19:28 UTC, Swolebrain commented on src/services/Authorization.js
> +	await SecureStore.deleteItemAsync('kk-idToken');
Please use Promise.all here so these aren't all sequential.

2021-04-21 19:28 UTC, Swolebrain commented on src/services/MixPanelAlt.js
> +import ExpoMixpanelAnalytics from '@benawad/expo-mixpanel-analytics';
is this file redundant?

2021-04-21 19:28 UTC, Swolebrain commented on src/stores/UserDataStore.js
> +		await SecureStore.setItemAsync('kk-idToken', idToken);
Please use Promise.all

2021-04-22 21:36 UTC, michaeldegori commented on src/routes/onboarding/OnboardingChoreSuggestionsContainer.js
> +			const existingChore = this.state.existingChores.find(eachChore => eachChore.name === chore.name);
Hmm, if it is, i'm having trouble seeing what else to do.

2021-04-26 14:41 UTC, Swolebrain approved these changes

2021-04-26 14:41 UTC, merged